// Evidence / report export screen.
const { Card: ECard, Button: EButton, Checkbox: ECheckbox, StatusBadge: EStatus, Badge: EBadge, Select: ESelect } = window.OpenMeshGuardDesignSystem_65348c;

function Evidence() {
  const d = window.OMG_DATA;
  const [sections, setSections] = React.useState({
    summary: true, mtls: true, authz: true, exposure: true, ownership: false, exceptions: true, drift: false,
  });
  const toggle = (k) => setSections((s) => ({ ...s, [k]: !s[k] }));
  const opts = [
    ['summary', 'Executive summary'],
    ['mtls', 'mTLS enforcement coverage'],
    ['authz', 'Authorization policy coverage'],
    ['exposure', 'Exposure & ingress risk'],
    ['ownership', 'Ownership & metadata gaps'],
    ['exceptions', 'Active & expiring exceptions'],
    ['drift', 'GitOps drift log'],
  ];
  const selected = Object.values(sections).filter(Boolean).length;

  return (
    <div style={{ display: 'grid', gridTemplateColumns: '1fr 340px', gap: 20, alignItems: 'start' }}>
      {/* Report builder */}
      <ECard title="Build evidence report" subtitle="Audit-ready export — no spreadsheets required">
        <div style={{ display: 'flex', gap: 12, marginBottom: 20 }}>
          <ESelect label="Scope" containerStyle={{ flex: 1 }} options={d.clusters.map((c) => ({ value: c, label: c })).concat([{ value: 'all', label: 'All clusters' }])} />
          <ESelect label="Framework" containerStyle={{ flex: 1 }} options={[{ value: 'soc2', label: 'SOC 2' }, { value: 'iso', label: 'ISO 27001' }, { value: 'pci', label: 'PCI DSS' }, { value: 'none', label: 'None (raw evidence)' }]} />
          <ESelect label="Format" containerStyle={{ width: 130 }} options={[{ value: 'pdf', label: 'PDF' }, { value: 'csv', label: 'CSV' }, { value: 'json', label: 'JSON' }]} />
        </div>
        <div className="omg-eyebrow" style={{ marginBottom: 12 }}>Sections</div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {opts.map(([k, label]) => (
            <div key={k} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', paddingBottom: 12, borderBottom: '1px solid var(--border-subtle)' }}>
              <ECheckbox checked={sections[k]} onChange={() => toggle(k)} label={label} />
              <EStatus status={k === 'ownership' || k === 'drift' ? 'warn' : 'pass'}>{k === 'ownership' || k === 'drift' ? 'Findings present' : 'Ready'}</EStatus>
            </div>
          ))}
        </div>
      </ECard>

      {/* Summary sidebar */}
      <ECard title="Report summary">
        <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 13 }}>
            <span style={{ color: 'var(--text-muted)' }}>Scope</span>
            <code style={{ fontFamily: 'var(--font-mono)' }}>prod-eu-1</code>
          </div>
          <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 13 }}>
            <span style={{ color: 'var(--text-muted)' }}>Sections</span>
            <span style={{ fontWeight: 600, color: 'var(--text-strong)' }}>{selected} of {opts.length}</span>
          </div>
          <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 13 }}>
            <span style={{ color: 'var(--text-muted)' }}>Findings included</span>
            <span style={{ fontWeight: 600, color: 'var(--text-strong)' }}>{d.metrics.openFindings}</span>
          </div>
          <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 13 }}>
            <span style={{ color: 'var(--text-muted)' }}>Generated by</span>
            <span>OpenMeshGuard v1.24</span>
          </div>
          <div style={{ height: 1, background: 'var(--border-subtle)' }} />
          <EButton variant="primary" fullWidth leftIcon={<Icon name="file-check" size={16} />}>Generate evidence (PDF)</EButton>
          <EButton variant="secondary" fullWidth leftIcon={<Icon name="clock" size={15} />}>Schedule monthly export</EButton>
          <p style={{ fontSize: 12, color: 'var(--text-muted)', textAlign: 'center', margin: 0 }}>Signed & timestamped. Retained for 12 months.</p>
        </div>
      </ECard>
    </div>
  );
}

window.Evidence = Evidence;
